# -*- coding: utf-8 -*-
"""diwali sales

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uG4tQk9MOmCEXIIiXizYc81sVaRZ4hOQ
"""

import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns

df=pd.read_csv('Diwali Sales Data.csv',encoding='unicode_escape')

df.head()

df.shape

df.info()

df.drop('Status',axis=1,inplace=True)

df.drop('unnamed1',axis=1,inplace=True)

df.info()

df.isnull().sum()

df.dropna(inplace=True)

df['Amount']=df['Amount'].astype(int)

df.describe()

df[['Age','Orders','Gender','Amount']].describe()



"""Exploratory Data Analysis"""

df.columns

# eda based on Gender
ac=sns.countplot(x='Gender',data=df)
for bars in ac.containers:
  ac.bar_label(bars)

sales_gender=df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)
sales_gender

sales_gender=df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)
sns.barplot(x="Gender",y='Amount',data=sales_gender)

"""from above graph we can see that most of the buyers are females"""

#Age

df.columns

ac=sns.countplot(data=df,x='Age Group',hue='Gender')

sales_age=df.groupby(['Age Group'],as_index=False)['Amount'].sum()
sns.barplot(data=sales_age,x='Age Group',y='Amount')

#State

sales_state=df.groupby(['State'],as_index=False)['Amount'].sum().head(10)
sns.set(rc={'figure.figsize':(15,5)})
sns.barplot(x='State',y='Amount',data=sales_state)

df.columns

#occupation
ac=sns.countplot(data=df,x='Occupation')
sns.set(rc={'figure.figsize':(15,5)})
for bars in ac.containers:
  ac.bar_label(bars)

occupation = df.groupby(['Occupation'], as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sns.set(rc={'figure.figsize':(22,5)})
sns.barplot(data = occupation, x = 'Occupation',y= 'Amount')

#product _category
product=df.groupby(['Product_Category'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=product,x='Product_Category',y='Amount')

